"use client";
 
import React, { useState } from "react";
import "./ai-video-generation.css";
 
// ─── FAQ data ────────────────────────────────────────────────────────────────
 
const FAQ_ITEMS = [
  {
    q: "What is an AI video generator?",
    a: "An AI video generator uses machine-learning models trained on millions of video clips to synthesise entirely new footage from a text description or a reference image. You type what you want to see — camera angle, subject, mood, lighting — and the model renders it frame-by-frame. Scenith uses state-of-the-art models including Kling 2.6 Pro, Wan 2.5, and Google Veo 3.1 to produce up to 1080p footage in seconds.",
  },
  {
    q: "How long does it take to generate a video?",
    a: "Most videos are ready within 30–120 seconds depending on the model, duration, and current queue. Wan 2.5 is the fastest option for quick iterations, while Kling 2.6 Pro and Veo 3.1 take slightly longer but produce higher-quality, more cinematically accurate results. You can watch the real-time status indicator on the page while your video renders.",
  },
  {
    q: "What video formats and resolutions are supported?",
    a: "All generated videos are delivered as MP4 files (H.264). Resolution depends on the model you choose: Wan 2.5 outputs 480p, while Kling 2.5 Turbo, Kling 2.6 Pro, Veo 3.1 Fast, and Veo 3.1 all output full 1080p. Supported aspect ratios are 16:9 (landscape), 9:16 (portrait for Reels/TikTok), and 1:1 (square for Instagram).",
  },
  {
    q: "Can I generate videos from an image?",
    a: "Yes — switch to 'Image to Video' mode, upload your reference image (PNG, JPG, or WEBP up to 10 MB), and describe the motion or action you want applied to it. The AI will animate your image while preserving the visual style and composition.",
  },
  {
    q: "What does 'native audio' mean and which models support it?",
    a: "Native audio means the AI generates matching sound effects, ambient audio, and sometimes music directly from the visual content — no separate audio editing required. Currently Veo 3.1 and Veo 3.1 Fast support native audio generation. Enabling audio costs 2× credits because it requires an additional generation pass.",
  },
  {
    q: "Do I own the videos I create?",
    a: "Yes. Videos you generate on Scenith using your account and credits are yours to use commercially and personally. We store them securely on our CDN so you can re-download them at any time from your generation history.",
  },
  {
    q: "What's the difference between the AI models?",
    a: "Each model has different strengths. Wan 2.5 is budget-friendly and fast, great for quick prototypes. Kling 2.5 Turbo offers 1080p at a mid-range credit cost with excellent motion consistency. Kling 2.6 Pro adds improved prompt adherence and cinematic camera movements. Veo 3.1 Fast is Google's high-speed 1080p model, and Veo 3.1 is the highest-quality option with native audio support and the most accurate scene composition.",
  },
  {
    q: "How do credits work?",
    a: "Credits are the currency for generating videos on Scenith. Each generation costs a fixed number of credits based on model, duration, and whether audio is enabled — costs are shown before you generate. Plans start at $9/month and include 300 credits. Unused credits roll over and your balance is always visible at the top of the generator.",
  },
  {
    q: "Can I use AI-generated videos on YouTube, Instagram, or TikTok?",
    a: "Yes. MP4 files generated by Scenith can be uploaded directly to any platform. For best results on YouTube and desktop, use 16:9 aspect ratio; for Reels and TikTok, use 9:16; for Instagram feed posts, use 1:1. We recommend disclosing AI-generated content where platform policies require it.",
  },
  {
    q: "What makes a good AI video prompt?",
    a: "The best prompts are specific about subject, action, environment, lighting, and camera style. For example: 'A close-up of a white coffee cup on a marble table, steam rising, warm morning light, shallow depth of field, cinematic 4K'. Avoid vague prompts like 'a nice video'. You can also use the negative prompt field to exclude things like 'blurry, watermark, low quality, shaky camera'.",
  },
];
 
// ─── Prompt tips data ─────────────────────────────────────────────────────────
 
const PROMPT_TIPS = [
  {
    label: "Cinematic Style",
    title: "Cinematic & Film Prompts",
    tips: [
      "Specify camera movement: dolly in, pan left, aerial orbit",
      "Add lighting cues: golden hour, neon rim light, overcast",
      "Name a visual style: Blade Runner, Studio Ghibli, National Geographic",
      "Include lens type: anamorphic, fisheye, telephoto 200mm",
    ],
    example: '"Aerial orbit of a moonlit Japanese castle, cherry blossoms falling, anamorphic lens flare, 4K cinematic"',
  },
  {
    label: "Nature & Landscape",
    title: "Nature & Environment Prompts",
    tips: [
      "Describe weather and atmosphere: storm clouds, morning mist, golden dusk",
      "Add motion to static scenes: waves crashing, leaves rustling",
      "Include scale reference: vast canyon, tiny flower close-up",
      "Pair with audio cues for Veo models: distant thunder, birdsong",
    ],
    example: '"Timelapse of storm clouds rolling over a desert mesa, lightning strikes, ultra-wide, National Geographic style"',
  },
  {
    label: "Product & Marketing",
    title: "Product & Brand Prompts",
    tips: [
      "Use clean backgrounds: white studio, gradient backdrop",
      "Describe product motion: rotating slowly, floating, water droplets",
      "Specify mood: premium, playful, minimalist, luxury",
      "Add finishing: bokeh, soft reflections, macro detail shot",
    ],
    example: '"Black luxury perfume bottle rotating on a wet marble surface, soft studio lighting, shallow depth of field, 4K"',
  },
  {
    label: "Negative Prompts",
    title: "What to Put in Negative Prompts",
    tips: [
      "Quality issues: blurry, grainy, low resolution, overexposed",
      "Artifacts: watermark, text overlay, distorted faces",
      "Motion issues: shaky cam, jump cuts, freeze frame",
      "Style exclusions: cartoon, sketch, black and white (if unwanted)",
    ],
    example: '"blurry, watermark, shaky camera, distorted, overexposed, low quality, stock footage look"',
  },
];
 
// ─── Component ────────────────────────────────────────────────────────────────
 
const VideoPageSEOSections: React.FC<{ onPromptSelect?: (p: string) => void }> = ({ onPromptSelect }) => {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
 
  const handlePromptClick = (raw: string) => {
    // Strip surrounding quotes that are part of display formatting
    const clean = raw.replace(/^[""]|[""]$/g, "");
    onPromptSelect?.(clean);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
 
  return (
    <>
      {/* ─── JSON-LD Structured Data ──────────────────────────────────────── */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "WebApplication",
                "@id": "https://scenith.in/tools/ai-video-generation#app",
                name: "Scenith AI Video Generator",
                url: "https://scenith.in/tools/ai-video-generation",
                applicationCategory: "MultimediaApplication",
                operatingSystem: "Web",
                description:
                  "Generate cinematic AI videos from text or images. Supports Kling 2.6 Pro, Wan 2.5, Veo 3.1. Up to 1080p, native audio, 5–10 second clips.",
                offers: {
                  "@type": "Offer",
                  price: "15.00",
                  priceCurrency: "USD",
                  description: "300 credits per month — enough for 6+ full HD videos",
                },
                featureList: [
                  "Text to Video generation",
                  "Image to Video animation",
                  "1080p resolution output",
                  "Native AI audio generation",
                  "Multiple AI models: Kling, Wan, Veo",
                  "16:9, 9:16, and 1:1 aspect ratios",
                  "MP4 download",
                ],
              },
              {
                "@type": "FAQPage",
                mainEntity: FAQ_ITEMS.map((item) => ({
                  "@type": "Question",
                  name: item.q,
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: item.a,
                  },
                })),
              },
              {
                "@type": "BreadcrumbList",
                itemListElement: [
                  { "@type": "ListItem", position: 1, name: "Home", item: "https://scenith.in" },
                  { "@type": "ListItem", position: 2, name: "Tools", item: "https://scenith.in/tools" },
                  { "@type": "ListItem", position: 3, name: "AI Video Generator", item: "https://scenith.in/tools/ai-video-generation" },
                ],
              },
            ],
          }),
        }}
      />
 
      {/* ─── Stats Strip ────────────────────────────────────────────────────── */}
      <div className="seo-stats-strip">
        {[
          { number: "1080p",  label: "Max Resolution Output" },
          { number: "5+",     label: "AI Models Available" },
          { number: "30s",    label: "Average Generation Time" },
          { number: "3",      label: "Aspect Ratios Supported" },
        ].map((s) => (
          <div className="seo-stat-cell" key={s.label}>
            <div className="seo-stat-number">{s.number}</div>
            <div className="seo-stat-label">{s.label}</div>
          </div>
        ))}
      </div>
 
      {/* ─── Features Grid ──────────────────────────────────────────────────── */}
      <section className="seo-section" aria-labelledby="features-heading">
        <div className="seo-divider" />
        <div className="seo-section-header">
          <span className="seo-eyebrow">Why Scenith</span>
          <h2 className="seo-section-title" id="features-heading">
            Everything you need to create AI videos
          </h2>
          <p className="seo-section-sub">
            Professional-grade tools. No video editing experience required.
          </p>
        </div>
        <div className="seo-features-grid">
          {[
            { icon: "🎬", title: "Multiple State-of-the-Art Models", desc: "Choose from Kling 2.6 Pro, Kling 2.5 Turbo, Wan 2.5, Veo 3.1 Fast, and Google Veo 3.1 — each optimised for different use cases and budgets." },
            { icon: "🖼️", title: "Image to Video Animation", desc: "Upload any reference image and describe the motion. The AI preserves your composition while adding fluid, realistic movement." },
            { icon: "🔊", title: "Native AI Audio", desc: "Veo 3.1 models generate matching ambient sound effects and audio directly from the visual content — no DAW required." },
            { icon: "📐", title: "All Aspect Ratios", desc: "Generate in 16:9 for YouTube and desktop, 9:16 for Reels and TikTok, or 1:1 for Instagram — all from the same prompt." },
            { icon: "⚡", title: "Fast Turnaround", desc: "Most generations complete in under 90 seconds. A live status indicator keeps you updated every 5 seconds so you never wonder what's happening." },
            { icon: "📥", title: "Instant MP4 Download", desc: "Your finished video is delivered as a high-quality MP4 file. Download immediately and use it anywhere — no watermarks on paid plans." },
            { icon: "🔒", title: "Secure & Private", desc: "Your prompts and videos are stored securely. Videos are served over a CDN with authenticated access — only you can see your history." },
            { icon: "💡", title: "Prompt Suggestions Built-In", desc: "Not sure what to type? One-click prompt suggestions help you get started instantly. Explore styles from cinematic to abstract." },
            { icon: "🔄", title: "Unlimited Iterations", desc: "Don't love the result? Tweak the prompt, swap the model, adjust duration, and regenerate as many times as your credits allow." },
          ].map((f) => (
            <div className="seo-feature-card" key={f.title}>
              <span className="seo-feature-icon">{f.icon}</span>
              <h3 className="seo-feature-title">{f.title}</h3>
              <p className="seo-feature-desc">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>
 
      {/* ─── Models Comparison ──────────────────────────────────────────────── */}
      <section className="seo-section" aria-labelledby="models-heading">
        <div className="seo-divider" />
        <div className="seo-section-header">
          <span className="seo-eyebrow">AI Models</span>
          <h2 className="seo-section-title" id="models-heading">
            Compare AI video generation models
          </h2>
          <p className="seo-section-sub">
            Each model has different strengths — pick the right one for your use case.
          </p>
        </div>
        <div className="seo-models-table-wrap">
          <table className="seo-models-table" role="table">
            <thead>
              <tr>
                <th>Model</th>
                <th>Resolution</th>
                <th>Audio</th>
                <th>Speed</th>
                <th>Best for</th>
                <th>Credits (5s)</th>
              </tr>
            </thead>
            <tbody>
              {[
                { name: "Wan 2.5",          res: "480p",  audio: false, badge: "seo-badge-budget",  badgeLabel: "Budget",  speed: "Fastest", best: "Drafts & prototypes",          cr: 46  },
                { name: "Kling 2.5 Turbo",  res: "1080p", audio: false, badge: "seo-badge-fast",    badgeLabel: "Fast",    speed: "Fast",    best: "Social media content",          cr: 64  },
                { name: "Kling 2.6 Pro",    res: "1080p", audio: false, badge: "seo-badge-quality", badgeLabel: "Quality", speed: "Medium",  best: "Cinematic & branded content",   cr: 64  },
                { name: "Veo 3.1 Fast",     res: "1080p", audio: true,  badge: "seo-badge-audio",   badgeLabel: "Audio",   speed: "Fast",    best: "Content with ambient audio",    cr: 92  },
                { name: "Veo 3.1",          res: "1080p", audio: true,  badge: "seo-badge-quality", badgeLabel: "Best",    speed: "Medium",  best: "Highest quality + native audio", cr: 186 },
              ].map((m) => (
                <tr key={m.name}>
                  <td className="seo-model-name-cell">{m.name}</td>
                  <td>{m.res}</td>
                  <td>{m.audio ? <span className="seo-check">✓</span> : <span className="seo-cross">✕</span>}</td>
                  <td><span className={`seo-badge ${m.badge}`}>{m.badgeLabel}</span></td>
                  <td>{m.best}</td>
                  <td style={{ color: "#818CF8", fontWeight: 600 }}>{m.cr} cr</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
 
      {/* ─── Use Cases ──────────────────────────────────────────────────────── */}
      <section className="seo-section" aria-labelledby="usecases-heading">
        <div className="seo-divider" />
        <div className="seo-section-header">
          <span className="seo-eyebrow">Use Cases</span>
          <h2 className="seo-section-title" id="usecases-heading">
            Who uses AI video generation?
          </h2>
          <p className="seo-section-sub">
            From solo creators to agencies — AI video fits every workflow.
          </p>
        </div>
        <div className="seo-usecases-grid">
          {[
            { icon: "📱", title: "Content Creators",        desc: "Generate Reels, TikToks, and YouTube Shorts without a camera or editing suite." },
            { icon: "🛍️", title: "E-commerce & Brands",     desc: "Create product showcase videos, ads, and brand films in minutes, not days." },
            { icon: "🎮", title: "Game Developers",          desc: "Prototype cutscenes, cinematic trailers, and concept videos before production." },
            { icon: "📰", title: "News & Media",             desc: "Visualise stories, data, or concepts with custom AI-generated b-roll footage." },
            { icon: "🎓", title: "Educators & Trainers",     desc: "Produce explainer videos, animated lessons, and course content at scale." },
            { icon: "🎨", title: "Artists & Designers",      desc: "Explore visual concepts, mood boards, and generative art in motion." },
            { icon: "🏢", title: "Marketing Agencies",       desc: "Rapidly iterate on ad concepts and deliver client previews without a production budget." },
            { icon: "🚀", title: "Startups & Founders",      desc: "Create demo videos, pitch deck animations, and landing page heroes with zero production cost." },
          ].map((u) => (
            <div className="seo-usecase-card" key={u.title}>
              <span className="seo-usecase-icon">{u.icon}</span>
              <h3 className="seo-usecase-title">{u.title}</h3>
              <p className="seo-usecase-desc">{u.desc}</p>
            </div>
          ))}
        </div>
      </section>
 
      {/* ─── Prompt Tips ────────────────────────────────────────────────────── */}
      <section className="seo-section" aria-labelledby="tips-heading">
        <div className="seo-divider" />
        <div className="seo-section-header">
          <span className="seo-eyebrow">Prompt Guide</span>
          <h2 className="seo-section-title" id="tips-heading">
            How to write great AI video prompts
          </h2>
          <p className="seo-section-sub">
            The quality of your output depends heavily on the quality of your prompt. Here's how to get the best results.
          </p>
        </div>
        <div className="seo-tips-grid">
          {PROMPT_TIPS.map((tip) => (
            <div className="seo-tip-card" key={tip.label}>
              <span className="seo-tip-label">{tip.label}</span>
              <h3>{tip.title}</h3>
              <ul>
                {tip.tips.map((t) => <li key={t}>{t}</li>)}
              </ul>
              <div
                className="seo-prompt-example"
                onClick={() => handlePromptClick(tip.example)}
                title="Click to use this prompt"
                role="button"
                tabIndex={0}
                onKeyDown={(e) => e.key === "Enter" && handlePromptClick(tip.example)}
              >
                {tip.example}
                <span>↑ Click to try this prompt</span>
              </div>
            </div>
          ))}
        </div>
      </section>
 
      {/* ─── FAQ ────────────────────────────────────────────────────────────── */}
      <section className="seo-section" aria-labelledby="faq-heading">
        <div className="seo-divider" />
        <div className="seo-section-header">
          <span className="seo-eyebrow">FAQ</span>
          <h2 className="seo-section-title" id="faq-heading">
            Frequently asked questions
          </h2>
          <p className="seo-section-sub">
            Everything you need to know about AI video generation on Scenith.
          </p>
        </div>
        <div className="seo-faq-list" role="list">
          {FAQ_ITEMS.map((item, i) => (
            <div
              className={`seo-faq-item ${openFaq === i ? "open" : ""}`}
              key={i}
              role="listitem"
            >
              <button
                className="seo-faq-question"
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                aria-expanded={openFaq === i}
              >
                <span>{item.q}</span>
                <span className="seo-faq-chevron" aria-hidden="true">▼</span>
              </button>
              <div className="seo-faq-answer" aria-hidden={openFaq !== i}>
                <p>{item.a}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
 
      {/* ─── CTA Banner ─────────────────────────────────────────────────────── */}
      <div className="seo-cta-banner" aria-label="Call to action">
        <h2>Start generating AI videos today</h2>
        <p>
          No video editing skills needed. No camera. No crew.
          Just type what you want to see.
        </p>
        <div className="seo-cta-buttons">
          <a href="/signup" className="seo-cta-primary">
            ✨ Get 50 Free Credits
          </a>
          <a href="/pricing" className="seo-cta-secondary">
            View Pricing →
          </a>
        </div>
      </div>
 
      {/* ─── Hidden long-form copy for SEO crawlers ─────────────────────────── */}
      <div className="seo-hidden" aria-hidden="true">
        <h2>AI Video Generator — Text to Video and Image to Video</h2>
        <p>
          Scenith is an AI video generation platform that lets you create cinematic videos from
          text prompts or reference images. Powered by the latest models from Kling AI, Wan, and
          Google Veo 3.1, Scenith produces MP4 videos at up to 1080p resolution with native audio.
          Whether you're a content creator, marketer, educator, or developer, Scenith makes
          professional AI video creation accessible without a production budget.
        </p>
        <p>
          Text to video generation: type a descriptive prompt and our models synthesise realistic
          footage from scratch. Image to video animation: upload any photo and describe the motion
          you want applied. Native AI audio: Veo 3.1 models generate matching ambient sound effects
          alongside the video. Multiple aspect ratios including 16:9 for YouTube and desktop, 9:16
          for Instagram Reels and TikTok, and 1:1 square format for social media feeds.
        </p>
      </div>
    </>
  );
};
 
export default VideoPageSEOSections;