import type { Metadata } from 'next';
import ToolsIndex from './ToolsClient';

export const metadata: Metadata = {
  title: 'Scenith Tools | AI-Powered Video & Media Tools - Free Online Suite',
  description:
    'Discover 6+ powerful AI tools for video editing, voice generation, subtitle creation, background removal, and more. Free online tools trusted by 50,000+ creators. No signup required.',
  keywords: [
    'scenith login',
    'video editor login',
    'free video editing account',
    'online video maker sign in',
    'scenith account login',
    'AI voice generator',
    'free text to speech',
    'text to speech online',
    'AI TTS tool',
    'voice generator free',
    'text to voice AI',
    'natural AI voices',
    'TTS online free',
    'speech synthesis',
    'voiceover generator',
    'AI audio generator',
    'free voice AI',
    'text to audio',
    'realistic TTS',
    'multi-language TTS',
    'AI subtitle generator',
    'add subtitles to video',
    'free subtitle editor',
    'video subtitle tool',
    'automatic subtitles AI',
    'subtitle video online',
    'customize video subtitles',
    'free subtitle generator',
    'video caption editor',
    'AI video subtitles',
    'subtitle styles',
    'video editing subtitles',
    'online subtitle maker',
    'professional video subtitles',
    'auto caption video',
    "free image editor",
    "online graphic design",
    "canva alternative",
    "design tool online",
    "image editor free",
    "graphic design software",
    "create social media graphics",
    "design banners online",
    "photo editor",
    "text to image",
    "shape editor",
    "filter editor",
    "free design tool",
    "web-based editor",
    "scenith editor",       
  ],
  openGraph: {
    title: 'Login to Scenith - Free Video Editor',
    description: 'Access your projects and start creating professional videos instantly with Scenith.',
    url: 'https://scenith.in/login',
    type: 'website',
    images: ['/images/og-login.jpg'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Scenith Login | Free Video Editor',
    description: 'Sign in to create stunning social media videos for free.',
    images: ['/images/twitter-login.jpg'],
  },
  alternates: {
    canonical: '/login',
  },
  robots: 'index, follow',
};

export default function ToolsPage() {
  return <ToolsIndex />;
}